customhost="database-1.cbr7awmahqbt.us-east-1.rds.amazonaws.com"
customuser="admin"
custompass="123456789"
customdb="studentdb"
custombucket="my-student"
# customregion=""
admin_name="Admin"
admin_pass="myadmin123"